### ISSUE TITLE
请问1.0现在release了吗？作者能不能发布到jitpack？

### ISSUE THREAD

**Issue by qiusunshine** [Edsuns/AdblockAndroid#4]
看代码感觉封装得非常方便和强大，想借鉴使用，但是发现仓库中Readme已经是1.0版本，而jitpack中最新版仍然是0.9.1，能否发布一下最新版呢？不胜感激

**Comment by Edsuns** [comment]
0.9.1已经包含所有最新的代码，使用0.9.1版本即可，readme里写了1.0只是示例。

**Comment by qiusunshine** [comment]
> 0.9.1已经包含所有最新的代码，使用0.9.1版本即可，readme里写了1.0只是示例。

好的，感谢回复
