### ISSUE TITLE
请问订阅不能自动刷新吗？

### ISSUE THREAD

**Issue by qiusunshine** [Edsuns/AdblockAndroid#5]
请问订阅不能自动刷新吗？貌似没看到相关代码

**Comment by Edsuns** [comment]
目前不支持

**Comment by qiusunshine** [comment]
> 目前不支持

好的，目前已额外加了更新逻辑来实现了，不过如果依赖直接支持可能会更好

另外这里的KEY_CHECK_LICENSE不能默认为false或者可以自定义吗？
![image](https://github.com/Edsuns/AdblockAndroid/assets/27729606/29aa3eef-0cdb-4d7e-b0cb-2d93fee67a41)

因为有些小众的订阅是没有license的，我现在是自定义WorkManager初始化来强制修改这个值，就是有点变扭
